#!/usr/bin/env node
/**
 * generate-nav.js
 * Reads menu-config.json and outputs nav-snippet.html
 * Supports nested children for dropdown menus
 * Usage: node generate-nav.js
 */

const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'menu-config.json');
const outputPath = path.join(__dirname, 'nav-snippet.html');

function renderItem(item, indent) {
  const pad = ' '.repeat(indent);
  const hasChildren = item.children && item.children.length > 0;

  if (!hasChildren) {
    return `${pad}<li class="lb-nav__item"><a class="lb-nav__link" href="${item.href}">${item.label}</a></li>`;
  }

  const childItems = item.children
    .map((child) => `${pad}      <li><a href="${child.href}">${child.label}</a></li>`)
    .join('\n');

  return `${pad}<li class="lb-nav__item lb-nav__item--has-dropdown">
${pad}  <a class="lb-nav__link" href="${item.href}">${item.label}</a>
${pad}  <ul class="lb-nav__dropdown">
${childItems}
${pad}  </ul>
${pad}</li>`;
}

try {
  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  const items = config.items || [];

  const listItems = items.map((item) => renderItem(item, 4)).join('\n');

  const dropdownCount = items.filter((i) => i.children && i.children.length).length;

  const html = `<!-- Generated by generate-nav.js — do not edit manually -->
<nav class="lb-nav" role="navigation" aria-label="Main navigation">
  <ul class="lb-nav__list">
${listItems}
  </ul>
</nav>
`;

  fs.writeFileSync(outputPath, html, 'utf8');
  console.log(
    `✓ nav-snippet.html generated (${items.length} items, ${dropdownCount} with dropdowns)`
  );
} catch (err) {
  console.error('Error generating nav:', err.message);
  process.exit(1);
}
